language: node_js

node_js:
  - "10"

services:
  - docker

sudo: required
dist: trusty

env:
  global:
    - VERBOSE=true

before_install:
  # Install a recent Docker version
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo add-apt-repository -y ppa:ansible/ansible
  - sudo apt-get update
  - sudo apt-get -y install docker-ce ansible

before_script:

script:
  - npm install
  - npm run lint
  - npm run generate
  - make api/dist 

deploy:
  - provider: script
    skip_cleanup: true
    script: make publish
    on:
      branch: master
